### ISSUE TITLE
[ALL] Feat: 게시판 댓글 기능 구현

### ISSUE THREAD

**Issue by yongsuson** [team-eungae/eungae-pediatric_appointment#269]
> 배경
- CommunityBoard에 댓글 기능 부재.

> 기대효과
- CommunityBoard 댓글 기능 구현

> 인수 조건
- PR후에 조원 밑 멘토님 코멘트 후 이상 없으면 merge

**Comment by ghktndyd** [comment]
기능이 딱히 필요할 것 같지 않아서 이슈를 종료합니다.
