### ISSUE TITLE
[BE] Fix: DoctorClosed 위치 변경

### ISSUE THREAD

**Issue by seanlee0923** [team-eungae/eungae-pediatric_appointment#94]
> 배경
- DoctorClosed 엔티티파일이 application 폴더에 위치함

> 기대효과
- 원래 있어야 하는 위치로 수정

> 인수 조건
- DoctorClosed 가 application이 아닌 domain 패키지로 이동

**Comment by ghktndyd** [comment]
패키지 경로 제가 한 번에 수정할게요 !
